### ISSUE TITLE
Update Chrome Extension (fbserve)

### ISSUE THREAD

**Issue by ddugovic** [anantdgoel/HackPrincetonF16#11]
I see that the server name is changing from `trustfb` to `fbserve` but unless you rebuild the extension, it will continue to point to the old server...

**Comment by anantdgoel** [comment]
This is not an issue. `fbserve` is our development server not our production server and is not supposed to be accessed by anyone but the core team (mainly because we don't want excess traffic crashing our development servers). I think the push to GitHub with this link was a mistake by one of the team members. We were not going to push `fbserve` link to Github.
